[package]
name = "bigbit"
version = "0.0.0"
authors = ["Kotauskas <v.toncharov@gmail.com>"]
edition = "2018"
description = "Implements the BigBig format, allowing for compact storage of arbitrarily large numbers."
readme = "README.md"
license = "Zlib"
keywords = ["bigbit", "bytebit", "bignum", "gmp", "num"]
categories = ["algorithms", "encoding", "mathematics", "no-std", "parser-implementations"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html